### PR TITLE
FME workbenchs that add style attributes while processing data

### PR DESCRIPTION
**Pull request by antcalatayud**
Hello,

Not sure if this will be useful... but today I had to process some MM data on FME and I needed to add the style_code to my data before inserting on PostgreSQL, so I created a few transformers.

I divided the transformers into different files to follow your naming conventions.

Please note, that I only added "style_code", but if you think this will be useful to other users, let me know and I will add the "style_description" as well.

Cheers

### CODE REVIEW

**Comment by TimJMartin** [comment]
Hi Antonio

This sounds really promising and has been on our backlog to do for ages. We will give them a try and will merge the request when the tests are completed.

Thanks for getting involved

Tim

**Comment by charleyglynn** [comment]
Hi @antcalatayud 

These workbenches are great and could be really useful for many users.
If possible, could you please add the "style_description" as mentioned above and then we will be happy to merge it in.

Many thanks
Charley

**Comment by antcalatayud** [comment]
Hi @charleyglynn, 

I just pushed the workbenches with the style descriptor. I didn't have time to test them properly.

Thanks,

Antonio

**Comment by charleyglynn** [comment]
Thanks @antcalatayud :thumbsup:

**Pull request merged**
